### ISSUE TITLE
[BUG] Able to pass anything as predicate

### ISSUE THREAD

**Issue by thomasttvo** [newdash/newdash#534]
I think this line should be removed from all array util functions. It makes them type-unsafe

```ts
export function find<T>(collection: ArrayLike<T>, predicate?, fromIndex?: number): T | undefined;
```

As an example where this fails to provide type safety:

```ts
find([] as {id: string}[], {id_: 2}) // no error, but there should be one
```

**Comment by Soontao** [comment]
sure, I'll check this later. thank you :)
